metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

replication_mode = "1"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "${BENTO_GARAGE_RPC_SECRET}"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.${BENTO_GARAGE_DOMAIN}"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${BENTO_GARAGE_ADMIN_TOKEN}"